baseURL: https://thankful-grass-0c6e2380f.1.azurestaticapps.net/
languageCode: en-us
title: WarAcme Site
theme: Universal
author:
  facebook: "https://facebook.com/warnov"
  twitter: "https://twitter.com/warnov"
  email: "warnov@gmail.com"
  name: "Acme Corporation by War"
  location: Bogoyork
  phone: (999) 999-9999
  hours: "Mon-Fri: 9:00AM - 6:00PM, ET"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 100
    - identifier: contact
      name: Contact
      url: /contact
      weight: 200
params:
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 WarNov Corp. All rights reserved."
  footer:
    - title: About
      content:   >
        Acme Corporation is the world's leading 
        manufacturer of digital shapes. From squares and 
        circles to triangles and hexagons, we have it 
        all. Browse through our collection of various 
        forms with different thicknesses and line styles. 
        We shape the world. You live in it. WarNov. Yeah!


    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true
  style: blue
  logo: /image/logo.png
  logo_small: /image/logo.png
  about_us:  >
    Acme Corporation is the world's leading manufacturer 
    of digital shapes. From squares and circles to 
    triangles and hexagons, we have it all. Browse through 
    our collection of various forms with different 
    thicknesses and line styles. We shape the world. 
    You live in it. Universal


  recent_posts:
    enable: true

      

